author:
  name: Jake Rayson
  email: hello@growdigital.org
baseURL: https://www.forestgarden.wales/
languageCode: en-GB
title: Forest Garden Wales
theme: gofgw
copyright: This work is dual-licensed under MIT & GPL v3
paginate: 10
pluralizeListTitles: false
summaryLength: 13
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
permalinks:
  article: /:title
params:
  description: Wildlife forest garden design for edible crops
  publisher: Forest Garden Wales
  publisherLogo: https://res.cloudinary.com/growdigital/image/upload/v1570899988/logo-fgw.png
  images:
    - https://res.cloudinary.com/growdigital/image/upload/v1570899988/logo-fgw.png
  cloudinary: https://res.cloudinary.com/growdigital/image/upload/
  talkyardServerUrl: https://comments-for-www-forestgarden-wales.talkyard.net
  email: hello@forestgarden.wales
  eventbrite: jake-rayson-17248421654
  facebook: NatureWorksGarden
  fbapp_id: 181804962563660
  linkedin: natureworksgarden
  pinterest: NatureWorksGarden
  tel: +447802535321
  tripadvisor: Attraction_Review-g580438-d13991813-Reviews-Forest_Garden_Wales-Newcastle_Emlyn_Carmfgarthenshire_Wales.html
  twitter: NatureWorksGdn
  wordpress: forestgardenwales
  youtube: NatureWorksGarden
